// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// code.cpp
int central_candidate_c(cpp11::integers x);
extern "C" SEXP _rSW2metrics_central_candidate_c(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(central_candidate_c(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _rSW2metrics_central_candidate_c(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rSW2metrics_central_candidate_c", (DL_FUNC) &_rSW2metrics_central_candidate_c, 1},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_rSW2metrics(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
